### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #6.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by PertuyF** [comment]
Missing `r-multicool` for R3.5.1

**Comment by PertuyF** [comment]
https://github.com/conda-forge/r-multicool-feedstock/pull/3

**Comment by PertuyF** [comment]
`r-multicool` now available, re-rendering.

@conda-forge-admin, please rerender

**Comment by PertuyF** [comment]
@conda-forge/r-ks Could you bump the build number? Then we should be good to go.

Bonus question: What should I do to gain write permission to a specific feedstock? Looks less straightforward to edit recipes with conda-forge than Bioconda.

**Comment by dbast** [comment]
Done via https://github.com/conda-forge/r-ks-feedstock/pull/8

**Pull request closed without merging**
